<?php

namespace AppBundle\Repository;

/**
 * HeadquarterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeadquarterRepository extends \Doctrine\ORM\EntityRepository
{
}
